# -*- coding: utf-8 -*-
# Part of Bim20. See LICENSE file for full copyright and licensing details.
from . import chat_bim
from . import bim_assets
from . import res_company
from . import res_partner
from . import bim_project
from . import bim_department
from . import bim_documentation
from . import bim_purchase_requisition
from . import bim_purchase_services
from . import bim_mobile_warehouse
from . import purchase
from . import res_users
from . import stock
from . import uom
from . import product_template
from . import account_move
from . import bim_paidstate
from . import bim_config
from . import bim_task
from . import bim_budget
from . import bim_concepts
from . import bim_miscellaneous
from . import bim_checklist
from . import ticket_bim_category
from . import ticket_bim
from . import bim_object
from . import bim_part
from . import hr_employee
from . import bim_ite
from . import work_order
from . import bim_list_price_agreed
from . import ir_config_parameter
from . import bim_massive_certification_by_line
from . import hr_attendance
from . import bim_extra_hour
from . import sale
from . import bim_cost_list
from . import bim_opening_balance
from . import bim_massive_chapter_certification
from . import bim_quality_config
from . import bim_quality_control_plan
from . import bim_project_limit
from . import bim_budget_cash_flow
from . import bim_budget_history
from . import bim_product_group
from . import bim_concepts_template_group
from . import bim_concepts_template
from . import bim_fuel_cost
from . import bim_equipment_cost
from . import bim_equipment_fuel
from . import bim_rent
from . import res_currency_rate
from . import bim_specialty
from . import bim_budget_resource
from . import bim_attribute
from . import bim_parameter
from . import bim_tool_use
from . import employee_tools
from . import bim_tool_deprecation
from . import bim_resource_template
from . import bim_budget_revit_import
from . import bim_boq_template
from . import bim_apu_template
from . import sale_order_line
from . import hr_attendance_mass
from . import virtual_product
from . import hr_attendance_mass_summary
from . import bim_client_hour
from . import bim_project_employee_timesheet_summary
from . import deliver_product
from . import massive_deliver_product
from . import hr_size
from . import hr_level_study
from . import bim_transport_equipment
from . import bim_transport_equipment_brand
from . import bim_transport_equipment_model
from . import tms_shipment
from . import transportation_expenses
from . import tms_expense_record
from . import datbase_concept_importer
from . import work_database_concept_importer
from . import product_pricelist
from . import bim_tool_rent
from . import chat_bin_prompt
from . import account_payment
from . import bim_recurring_contract
from . import budget_category
from . import certification_index
from . import customer_question
from . import customer_question_template
from . import customer_survey
from . import budget_request
from . import bim_marketing_campaign
from . import analitic_account_control
from . import bim_update
from . import virtual_product_category
from . import purchase_departure
from . import project_estimate
from . import picking_analysis
from . import fleet_vehicle
from . import other_expense
from . import bim_general_config
from . import project_parameter
from . import bim_expenses_import
from . import bim_sql_report
from . import bim_template_xls
from . import bim_cash_flow
from . import bim_cash_flow_generator
from . import bim_cash_flow_category
from . import contractor_contract
from . import contractor_contract_generator
from . import contractor_contract_progress_capture
from . import contractor_contract_analysis
from . import real_estate_development
from . import real_estate_property
from . import real_estate_block
from . import real_estate_lot
from . import real_estate_prototype
from . import real_estate_state
from . import real_estate_sale_order
from . import real_estate_quota
from . import real_estate_price_list
from . import real_estate_property_variant
from . import bim_server
from . import bim_model
from . import bim_bucket
from . import maintenance_type_task
from . import maintenance_category
from . import maintenance_location
from . import maintenance_task_plan
from . import maintenance_task
from . import maintenance_sub_task
from . import maintenance_part
from . import maintenance_asset
from . import maintenance_resource
from . import maintenance_measure
from . import maintenance_work_request
from . import work_resources_contract
from . import assistance_importer
from . import framework_contract
from . import bim_mto
from . import diary_part
from . import resource_analysis
from . import bim_rfi
from . import bim_element_type
from . import bim_element
from . import bim_boq
from . import bim_ai_model
from . import cost_settlement
from . import concept_phase
from . import concept_specialty
from . import bim_pcp
from . import work_breakdown
from . import daily_part_liquidation
from . import purchase_valuation
from . import employee_category
from . import employee_specialty
from . import employee_location
from . import employee_shift
from . import employee_bim_payroll
from . import cause_lost_hour
from . import lost_hour
from . import bi_week
from . import daily_part_report
from . import employee_discipline
from . import employee_area
from . import bi_ro
from . import cost_date
from . import bim_purchase_report
from . import bim_expense
from . import account_payment_register
from . import resource_balancing
from . import measurement_origin
from . import measurement_capture
from . import result_table
from . import resource_demand
from . import partner_attendance
from . import partner_attendance_contract
from . import bim_change_order
from . import bim_rubro
from . import bim_calendar
from . import income_statement_summary
from . import revit_budget_import
from . import bim_rq
from . import bim_mass
from . import maintenance_equipment
from . import employee_documentation
from . import employee_dcategory
from . import budget_exit
from . import closing_expenses