# -*- coding: utf-8 -*-
# Part of Bim20. See LICENSE file for full copyright and licensing details.
##############################################################################
#
#    BIM 2.0
#    This module copyright (C) 2026 Marlon Falcón Hernandez
#    check the license in the root of the module.
#    (<http://www.bim20.com>).
#
##############################################################################

{
    'name': 'BASE BIM 2.0 MFH',
    'version': '19.0.19.04.2026',
    'author': "Marlon Falcon Hernandez",
    'maintainer': 'Marlon Falcon Hernandez',
    'website': 'http://www.bim20.com',
    'license': 'AGPL-3',
    'category': 'Construction',
    'summary': 'Module BIM 2.0 for Managing Construction Projects',
    'depends': [
        'account',
        'fleet',
        'analytic',
        'base',
        'hr',
        'mail',
        'product',
        'purchase',
        'stock',
        'picking_standard_price',
        'sale',
        'sale_management',
        'hr_attendance',
        'uom',
        'folder_view',
        'sitemap_view',
        'purchase_requisition',
        'purchase_stock',
        'tree_excel_export',
        'maintenance',
    ],

    'description': """
BIM 2.0
============================
* Obras
* Presupuestos
* Certificaciones
* Recursos
* Reportes
* Checklist
* Integración con BC3.
        """,
    'data': [
        'data/parameter.xml',
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
        'data/ir_config_parameter.xml',
        'data/product_data.xml',
        'data/dp_data.xml',
        'data/data_bim_template_xls.xml',
        'data/analytic_plan.xml',
        'data/formula_data.xml',
        'data/bim_assets_data.xml',
        'data/bim_budget_space.xml',
        'data/bim_update_data.xml',
        'data/bim_general_config_data.xml',
        'data/data_bim_sql_report.xml',
        'security/security_groups_bim.xml',
        'wizard/bim_concept_template_copy_views.xml',
        'wizard/bim_resource_template_wizard.xml',
        'wizard/bim_project_stock_location_view.xml',
        'wizard/create_purchase_wizard_view.xml',
        'wizard/load_employees_view.xml',
        'wizard/load_week_hours_view.xml',
        'wizard/bim_budget_report.xml',
        'wizard/bim_certification_report.xml',
        'wizard/bim_resource_report.xml',
        'wizard/bim_clone_budget.xml',
        'wizard/bim_budget_stage_generate.xml',
        'wizard/load_template_checklist.xml',
        'wizard/copy_measures.xml',
        'wizard/load_resource_purchase_requisition.xml',
        'wizard/bim_purchase_requisition_space.xml',
        'wizard/bim_ajust_budget_wzd.xml',
        'wizard/bim_in_out_stock_mobile.xml',
        'wizard/bim_price_massive_wzd.xml',
        'wizard/employee_attendance_wzd_view.xml',
        'wizard/liquidate_stock_wzd_view.xml',
        'wizard/bim_create_task_wzd.xml',
        'wizard/bim_delete_concept_wzd.xml',
        'wizard/accumulated_delivery_report.xml',
        'wizard/individual_delivery_report.xml',
        'wizard/bim_analysis_wizard.xml',
        'wizard/hr_attendance_export_wzd_views.xml',
        'views/bim_opening_balance_view.xml',
        'views/bim_part_view.xml',
        'views/bim_extra_hour_view.xml',
        'views/bim_assets_views.xml',
        'views/bim_checklist_views.xml',
        'views/bim_specialty_view.xml',
        'views/bim_department_view.xml',
        'views/bim_expenses_import_views.xml',
        'views/certification_index_views.xml',
        'views/budget_category_views.xml',
        'views/bim_update_views.xml',
        'views/bim_miscellaneous_view.xml',
        'views/bim_ite_view.xml',
        'views/bim_apu_template_view.xml',
        'views/bim_cost_list_view.xml',
        'views/bim_mobile_warehouse_view.xml',
        'views/bim_product_group_view.xml',
        'views/bim_purchase_requisition_view.xml',
        'wizard/load_resource_purchase_service.xml',
        'views/bim_purchase_service_view.xml',
        'views/hr_attendance_mass_view.xml',
        'views/hr_attendance_mass_summary_views.xml',
        'views/virtual_product_view.xml',
        'views/virtual_product_category_views.xml',
        'views/bim_client_hour_views.xml',
        'views/deliver_products_motive_view.xml',
        'views/hr_size_views.xml',
        'views/bim_calendar_views.xml',
        'views/deliver_products_view.xml',
        'views/massive_deliver_products_view.xml',
        'views/res_company_view.xml',
        'views/hr_level_study_views.xml',
        'views/bim_report_views.xml',

        'views/bim_transport_equipment_brand_views.xml',
        'views/bim_transport_equipment_model_views.xml',
        'views/bim_transport_equipment_views.xml',
        'views/tms_expense_record_views.xml',
        'views/tms_shipment_views.xml',
        'views/transportation_expenses_views.xml',
        'views/product_pricelist_view.xml',
        'views/bim_rent_views.xml',
        'views/bim_tool_rent_views.xml',
        'views/analitic_account_control_views.xml',
        'views/chat_bim_views.xml',
        'views/chat_bim_prompt_views.xml',
        'views/purchase_departure_views.xml',
        'views/picking_analysis_views.xml',
        'views/fleet_vehicle_price_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/other_expense_views.xml',
        'views/bim_marketing_campaign_views.xml',
        'views/bim_cash_flow_views.xml',
        'views/bim_cash_flow_generator_views.xml',
        'views/bim_cash_flow_category_views.xml',
        'views/ticket_bim_view.xml',
        'views/ticket_bim_category_view.xml',
        'views/bim_general_config_views.xml',
        'views/bim_sql_report_views.xml',
        'views/contractor_contract_views.xml',
        'views/contractor_contract_generator_views.xml',
        'views/contractor_contract_progress_capture_views.xml',
        'views/contractor_contract_analysis_views.xml',
        'views/bim_server_views.xml',
        'views/bim_bucket_views.xml',
        'views/bim_model_views.xml',
        'views/cost_date_views.xml',

        'views/bim_resource_template_views.xml',
        'views/maintenance_type_task_views.xml',
        'views/maintenance_category_views.xml',
        'views/maintenance_location_views.xml',
        'views/maintenance_task_plan_views.xml',
        'views/maintenance_activator_views.xml',
        'views/maintenance_sub_task_views.xml',
        'views/maintenance_part_views.xml',
        'views/maintenance_task_views.xml',
        'views/maintenance_asset_views.xml',
        'views/maintenance_resource_views.xml',
        'views/maintenance_measure_views.xml',
        'views/maintenance_work_request_views.xml',
        'views/work_resources_contract_views.xml',
        'views/assistance_importer_views.xml',
        'views/framework_contract_views.xml',
        'views/bim_mto_views.xml',
        'wizard/diary_part_wizard_views.xml',
        'views/diary_part_views.xml',
        'views/resource_analysis_views.xml',
        'views/bim_rfi_views.xml',
        'views/bim_rq_views.xml',
        'views/bim_element_type_views.xml',
        'views/bim_element_views.xml',
        'views/bim_boq_views.xml',
        'views/bim_ai_model_views.xml',
        'views/cost_settlement_views.xml',
        'views/concept_phase_views.xml',
        'views/concept_specialty_views.xml',
        'views/bim_pcp_views.xml',

        'data/maintenance_data.xml',
        'views/work_breakdown_views.xml',
        'views/daily_part_liquidation_views.xml',
        'views/purchase_valuation_views.xml',



        'views/lost_hour_views.xml',

        'views/daily_part_report_views.xml',

        'views/bi_ro_views.xml',
        'views/result_table_views.xml',
        'views/bim_purchase_report_views.xml',
        'views/bim_expense_views.xml',
        'views/resource_balancing_views.xml',
        'views/resource_demand_views.xml',

        'views/partner_attendance_views.xml',
        'views/partner_attendance_contract_views.xml',
        'views/bim_change_order_views.xml',
        'views/bim_rubro_views.xml',
        'views/income_statement_summary_views.xml',
        'wizard/income_statement_import_wizard_views.xml',
        'views/revit_budget_import_views.xml',
        'views/bim_mass_views.xml',
        'views/employee_documentation_views.xml',
        'views/employee_dcategory_views.xml',
        'views/budget_exit_views.xml',
        'views/closing_expenses_views.xml',

        'views/menuitems_view.xml',
        'views/measurement_origin_views.xml',
        'views/measurement_capture_views.xml',

        'views/project_estimate_views.xml',
        'views/bim_project_employee_timesheet_summary_views.xml',
        'views/bim_tool_use_view.xml',

        'wizard/bim_import.xml',
        'wizard/bim_export.xml',
        'wizard/bim_stock_report.xml',
        'wizard/bim_paidstate_wizard.xml',
        'wizard/bim_paidstate_cancel_wizard.xml',
        'wizard/bim_budget_history_wzd.xml',
        'wizard/bim_budget_history_compare_wzd.xml',
        'wizard/bim_apu_wizard.xml',
        'wizard/bim_sand_box_wizard.xml',

        'views/bim_project_view.xml',
        'views/bim_task_view.xml',
        'views/bim_documentation_view.xml',
        'views/bim_template_xls_views.xml',

        'views/customer_question_views.xml',
        'views/customer_question_template_views.xml',
        'views/customer_survey_views.xml',

        'views/bim_recurring_contract_views.xml',
        'reports/report_header_template.xml',
        'reports/budget_departure_asset_discount_report.xml',
        'reports/budget_departure_list_report.xml',
        'reports/certifcation_by_line_report.xml',
        'reports/budget_request_report.xml',
        'reports/reports.xml',
        'wizard/bim_budget_clean_wzd.xml',
        'views/bim_budget_view.xml',
        'views/budget_request_views.xml',
        'views/uom_view.xml',
        'views/purchase_order_view.xml',
        'views/stock_view.xml',
        'views/account_move_view.xml',
        'views/paidstate_view.xml',

        'wizard/bim_product_update_wzd.xml',
        'wizard/virtual_product_wizard.xml',
        'views/product_view.xml',
        'views/bim_project_employee_view.xml',
        'views/bim_project_timesheet_view.xml',
        'views/bim_project_outsourcing_view.xml',
        'views/bim_budget_history_view.xml',
        'wizard/bim_concept_template_update_wzd.xml',
        'wizard/bim_concept_template_parameter_update_wzd.xml',
        'wizard/hr_deliver_products_view.xml',
        'views/bim_concept_template_view.xml',
        'views/bim_concept_template_group_view.xml',
        'wizard/bim_bc3.xml',
        'wizard/bim_ite.xml',
        'wizard/concept_assistant_views.xml',
        'wizard/bim_concept_template_wzd.xml',
        'wizard/bim_virtual_product_wizard_views.xml',
        'views/bim_concepts_view.xml',
        'views/sale_order_view.xml',
        'security/ir.model.access.csv',
        'views/bim_config.xml',

        'views/bim_project_state.xml',
        'views/bim_budget_state.xml',
        'views/bim_checklist_state.xml',
        'views/bim_quality_config_views.xml',
        'views/bim_quality_control_view.xml',
        'views/bim_massive_certification_by_line_view.xml',
        'views/bim_massive_chapter_certification_view.xml',
        'reports/external_layout.xml',
        'reports/multiple_real_execute_report.xml',
        'reports/quality_control_report.xml',
        'reports/programming_budget_report.xml',
        'reports/budget_report.xml',
        'reports/summary_report.xml',
        'reports/resource_report.xml',
        'reports/checklist_report.xml',
        'reports/certification_report.xml',
        'reports/origin_cert_report.xml',
        'reports/compare_cert_report.xml',
        'reports/real_execute_report.xml',
        'reports/real_execute_detailed_report.xml',
        'reports/real_execute_full_detailed_report.xml',
        'reports/multiple_cost_detailed_report.xml',
        'reports/report_work_order.xml',
        'reports/budget_stage_report.xml',
        'reports/bim_rfi_report.xml',
        'data/mail_template_checklist.xml',
        'reports/budget_notes_report.xml',
        'reports/document_notes_report.xml',
        'reports/attendance_work_report.xml',
        'reports/attendance_summary_report.xml',
        'reports/timesheet_summary_report.xml',
        'reports/purchase_valuation_report.xml',

        'data/ticket_bim_data.xml',
        'data/size_data.xml',
        'data/mail_template.xml',
        'data/chat_bim_prompt_data.xml',
        'views/bim_object_view.xml',
        'views/hr_employee_view.xml',
        'views/hr_attendance_view.xml',

        'views/res_partner_view.xml',
        'wizard/bim_budget_compare.xml',
        'wizard/bim_gantt_export.xml',
        'wizard/bim_gantt_import.xml',
        'wizard/bim_file_import.xml',
        'wizard/bim_budget_actions_view.xml',
        'views/res_currency_rate_view.xml',
        'views/bim_attribute_view.xml',
        'views/bim_parameter_view.xml',

        'views/employee_tools_view.xml',
        'views/account_payment_register_views.xml',

        'views/employee_category_views.xml',
        'views/employee_specialty_views.xml',
        'views/employee_location_views.xml',
        'views/employee_shift_views.xml',
        'views/employee_bim_payroll_views.xml',
        'views/cause_lost_hour_views.xml',
        'views/bi_week_views.xml',
        'views/employee_discipline_views.xml',
        'views/employee_area_views.xml',

        'views/bim_tool_deprecation_view.xml',
        'views/stock_location_view.xml',
        'views/bim_budget_revit_import_view.xml',
        'views/bim_boq_template_views.xml',
        'wizard/project_employee_attendance_wzd_view.xml',
        'wizard/bim_budget_resource_compare.xml',
        'wizard/bim_concept_template_import.xml',
        'wizard/bim_concept_template_export.xml',
        'wizard/bim_sale_budget.xml',
        'views/database_concept_importer.xml',
        'views/work_database_concept_importer.xml',
        'wizard/concept_from_database.xml',
        'wizard/bim_paidstate_mass_wzd.xml',
        'views/res_user_view.xml',
        'views/account_payment_views.xml',

        'security/security_groups_development.xml',
        'views/real_estate_development_views.xml',
        'views/real_estate_block_views.xml',
        'views/real_estate_lot_views.xml',
        'views/real_estate_prototype_views.xml',
        'views/real_estate_property_views.xml',
        'views/real_estate_state_views.xml',
        'views/real_estate_sale_order_views.xml',
        'views/real_estate_quota_views.xml',
        'views/real_estate_property_variant_views.xml',
        'views/real_estate_price_list_views.xml',
        'views/real_estate_menu_views.xml',

        'security/company_data.xml',
    ],
     'assets': {
        'web.assets_backend': [
            'base_bim_2/static/src/views/sitemap/*',
            'base_bim_2/static/src/views/sitemap/sitemap_styles.scss',
        ],
    },

    'installable': True,
    'auto_install': False,
    'demo': [],
    'test': [],
}
